source 'https://rubygems.org'

gem 'httparty'
gem 'dotenv'
gem 'google-cloud-vision'
gem 'minitest'
gem 'minitest-reporters'
gem 'mini_magick'
gem 'sinatra'
gem 'webrick'
gem 'rackup'
gem 'rack-test' 